import torch
from pymongo import MongoClient
from input import load_lookup, decode_state
from net import NN
import time

DB_URL = "mongodb://admin:4wj62MDCv%25X%5ErU3F@172.31.30.235:27017/"

device = torch.device("cuda")
client = MongoClient(DB_URL)
lookup = load_lookup(client["chesto"], device)

torch.set_float32_matmul_precision('high')
state = {'partyEnc': 'AADAQAAAAAAAAAAAAAAAAAAAAAAAAMBAAAAAAAAAwEAAAAAAAAAAAAAAAAAAAAAAAADAQAAAAAA=', 'userEnc': 'AACAP3d39z53d/c+VVXVPq5HoT4s+cU+rkehPjfQaT4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUBvo+1Ab6Pp020D5qA50+zcyMPmZmpj4YS34+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv1gSP79YEj+F65E+mpmZPq5HoT75xZI+BzptPgAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKDTxj6g08Y+3t3dPrHklz5gLHk+YCx5PnE9ij4AAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADaQOc+2kDnPgrXoz4OdJo+FK7HPn6xpD5I4bo+AAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMJb8PjCW/D6amdk+agOdPhhLfj5qA50+TxuoPgAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAP1yPAj9cjwI/SOG6PhERkT7QaYM+pw20PvYoXD4AAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'activeIdx': 'AAAAAAAAAAA=', 'moveChoiceIdx': 'swEAAMoAAAByAQAAcQEAAA==', 'moveMask': 'AQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAA=', 'switchMask': 'AAAAAAEAAAABAAAAAQAAAAEAAAABAAAA'}
device = torch.device("cuda")
nn = NN(lookup).to(device)
nn = torch.compile(nn, mode="reduce-overhead")
batch = decode_state([state] * 100, device=device)

# Warmup - important to ensure GPU is initialized and running at full speed
for _ in range(10):
    nn(batch)
torch.cuda.synchronize()  # Make sure all operations are complete

# Timing loop
start_time = time.time()
for _ in range(1000):
    nn(batch)
torch.cuda.synchronize()  # Wait for all operations to complete
end_time = time.time()

total_time = end_time - start_time
avg_time_per_inference = total_time / 100 * 1000  # Convert to milliseconds

print(f"Total time for 100 inferences: {total_time:.4f} seconds")
print(f"Average time per inference: {avg_time_per_inference:.4f} ms")