[project]
name = "model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.13",
    "fastapi>=0.115.11",
    "httpx>=0.28.1",
    "line-profiler>=4.2.0",
    "matplotlib>=3.10.1",
    "msgpack>=1.1.0",
    "pybase64>=1.4.1",
    "pymongo>=4.11.3",
    "tensorboard>=2.19.0",
    "torch>=2.6.0",
    "torch-tb-profiler>=0.4.3",
    "torch-tensorrt>=2.6.0",
    "torchvision>=0.21.0",
    "uvicorn>=0.34.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
ext-modules = [
    {name = "streaming_form_data._parser", sources = ["src/streaming_form_data/_parser.c"]}
]
